// ------------------------------------------------
// This file is auto-generated by createWriteContractQueries.js
// ------------------------------------------------

import { useWriteContract } from "wagmi";
import { useSSVNetworkDetails } from "@/lib/hooks/use-ssv-network-details";
import {
  TestnetEvent,
  MutationOptions,
  useWaitForTransactionReceipt_Testnet,
} from "@/lib/contract-interactions/utils/useWaitForTransactionReceipt";
import { HoleskyV4SetterABI } from "@/lib/abi/holesky/v4/setter";
import type { ExtractAbiFunction } from "abitype";
import {
  AbiInputsToParams,
  paramsToArray,
  extractAbiFunction,
} from "@/lib/contract-interactions/utils";
import type { WriteContractErrorType } from "@wagmi/core";

type Fn = ExtractAbiFunction<
  typeof HoleskyV4SetterABI,
  "setOperatorsPublicUnchecked"
>;
const abiFunction = extractAbiFunction(
  HoleskyV4SetterABI,
  "setOperatorsPublicUnchecked",
);
// type State = "idle" | "confirming" | "mining" | "mined" | "error";

export const useSetOperatorsPublicUnchecked_Testnet = (
  options?: MutationOptions<TestnetEvent>,
) => {
  const { setterContractAddress } = useSSVNetworkDetails();

  const wait = useWaitForTransactionReceipt_Testnet();
  const mutation = useWriteContract({
    mutation: {
      onSuccess: (result) => {
        wait.mutate(result, {
          onSuccess: (receipt) => {
            options?.onMined?.(receipt);
          },
        });
        options?.onConfirmed?.(result);
      },
      onError: (error) =>
        options?.onConfirmationError?.(error as WriteContractErrorType),
    },
  });

  const write = (params: AbiInputsToParams<Fn["inputs"]>) => {
    return mutation.writeContract({
      abi: HoleskyV4SetterABI,
      address: setterContractAddress,
      functionName: "setOperatorsPublicUnchecked",
      args: paramsToArray({ params, abiFunction }),
    });
  };

  const isLoading = mutation.isPending || wait.isPending;

  return {
    error: mutation.error || wait.error,
    isLoading,
    mutation,
    write,
  };
};
