// ------------------------------------------------
// This file is auto-generated by createWriteContractQueries.js
// ------------------------------------------------

import { useWriteContract } from "wagmi";
import { useSSVNetworkDetails } from "@/lib/hooks/use-ssv-network-details";
import {
  MainnetEvent,
  MutationOptions,
  useWaitForTransactionReceipt,
} from "@/lib/contract-interactions/utils/useWaitForTransactionReceipt";
import { MainnetV4SetterABI } from "@/lib/abi/mainnet/v4/setter";
import type { WriteContractErrorType } from "@wagmi/core";

// type State = "idle" | "confirming" | "mining" | "mined" | "error";

export const useAcceptOwnership = (options?: MutationOptions<MainnetEvent>) => {
  const { setterContractAddress } = useSSVNetworkDetails();

  const wait = useWaitForTransactionReceipt();
  const mutation = useWriteContract({
    mutation: {
      onSuccess: (result) => {
        wait.mutate(result, {
          onSuccess: (receipt) => {
            options?.onMined?.(receipt);
          },
        });
        options?.onConfirmed?.(result);
      },
      onError: (error) =>
        options?.onConfirmationError?.(error as WriteContractErrorType),
    },
  });

  const write = () => {
    return mutation.writeContract({
      abi: MainnetV4SetterABI,
      address: setterContractAddress,
      functionName: "acceptOwnership",
    });
  };

  const isLoading = mutation.isPending || wait.isPending;

  return {
    error: mutation.error || wait.error,
    isLoading,
    mutation,
    write,
  };
};
