// ------------------------------------------------
// This file is auto-generated by createWriteContractQueries.js
// ------------------------------------------------

import { useWriteContract } from "wagmi";
import { useSSVNetworkDetails } from "@/hooks/useSSVNetworkDetails";
import { MainnetV4SetterABI } from "@/abi/mainnet/v4/setter";
import type {
  ExtractAbiFunction,
  AbiParametersToPrimitiveTypes,
} from "abitype";

type Fn = ExtractAbiFunction<typeof MainnetV4SetterABI, "upgradeToAndCall">;

export const useUpgradeToAndCall = () => {
  const { setterContractAddress } = useSSVNetworkDetails();
  const mutation = useWriteContract();

  const write = (
    args: AbiParametersToPrimitiveTypes<Fn["inputs"]>,
    value?: bigint,
  ) => {
    return mutation.writeContract({
      value,
      abi: MainnetV4SetterABI,
      address: setterContractAddress,
      functionName: "upgradeToAndCall",
      args,
    });
  };

  return {
    mutation,
    write,
  };
};
