name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies and build
        run: |
          pnpm preinstall
          pnpm install
          VITE_SSV_NETWORKS='[{"networkId":17000,"api":"https://api.stage.ssv.network/api","apiVersion":"v4","apiNetwork":"holesky","explorerUrl":"https://holesky-explorer.stage.ssv.network","insufficientBalanceUrl":"https://faucet.stage.ssv.network","googleTagSecret":"GTM-K3GR7M5","tokenAddress":"0x68A8DDD7a59A900E0657e9f8bbE02B70c947f25F","setterContractAddress":"0x0d33801785340072C452b994496B19f196b7eE15","getterContractAddress":"0x656d5cC4e7d49EaCC063cBB8D3e072F2841D68b4"}]' && pnpm run build
          npx sematic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
