name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: |
          pnpm preinstall
          pnpm install
          pnpm run build
          npx sematic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
